version: "3.7"
services:
  backend:
    container_name: Ping-Pong-App
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "8080:8080"
volumes:
  node_modules: